default:
  #群通知类 仅群通知类支持单独配置
  groupMessage: false #群消息
  grouptemporaryMessage: false #群临时消息
  groupRecall: false #群撤回
  groupInviteRequest: false #群邀请
  groupAdminChange: false #群管理变动
  groupNumberChange: false #群聊列表变动
  groupMemberNumberChange: false #群成员变动
  addGroupApplication: false #加群申请
  #好友通知类
  privateMessage: false #好友消息
  PrivateRecall: false #好友撤回
  friendRequest: false #好友申请
  friendNumberChange: false #好友列表变动
  #其他通知
  botBeenBanned: false #禁言
  #其他设置
  notificationsAll: false #全部通知
  msgSaveDeltime: 600 #消息删除保存时间用于撤回消息通知

# 群单独配置 noMerge
123456:
  groupMessage: false #群消息

# bot单独配置 noMerge
bot:7891011:
  privateMessage: false #好友消息

#bot群单独设置 noMerge
bot:13456:123456:
  groupMessage: false #群消息
